version: '3.1'

services:

  app:
    container_name: guestbook
    image: iesgn/guestbook
    restart: always
    ports:
      - 83:80
    depends_on:
      - db

  db:
    container_name: redis
    image: redis
    restart: always