version: '3.9'

services:

    apache-service:
      container_name: ServidorwebApache
      image: httpd:latest
      cpus: 1.5
      mem_limit: 2048m
      restart: always
      ports:
       - "80:80"